# Generated by Django 4.2.13 on 2024-08-24 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название значка')),
                ('image', models.ImageField(upload_to='badges/', verbose_name='Изображение значка')),
                ('description', models.TextField(blank=True, verbose_name='Описание значка')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='RegRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фракция',
                'verbose_name_plural': 'Фракция',
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('message', models.TextField(verbose_name='Текст обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
            },
        ),
        migrations.CreateModel(
            name='ProfileConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен подтверждения',
                'verbose_name_plural': 'Токены подтверждения',
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=255, verbose_name='Тип изменения')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Логи изменений',
                'verbose_name_plural': 'Логи изменений',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('surnames', models.CharField(blank=True, max_length=25, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=40, verbose_name='Электронная почта')),
                ('photo', models.ImageField(blank=True, default='../static/images/incognito.png', upload_to='users/%Y/%m/%d', verbose_name='Фото')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('nick_name', models.CharField(blank=True, max_length=50, verbose_name='Игровой ник')),
                ('profile_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение профиля')),
                ('role_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение должности')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('last_viewed_news', models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение новостей')),
                ('last_viewed_changes', models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение истории изменений')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('badges', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.badge', verbose_name='Значки')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
                ('reg_role', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.regrole', verbose_name='Фракция')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.role', verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='InvestigationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя заявителя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия заявителя')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_details', models.TextField(verbose_name='Контактные данные')),
                ('image', models.ImageField(blank=True, null=True, upload_to='investigation_requests/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('confirmed_by_admin', models.BooleanField(default=False, verbose_name='Подтверждено администратором')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='profiles.profile', verbose_name='Назначено профилю')),
            ],
            options={
                'verbose_name': 'Заявление на расследование',
                'verbose_name_plural': 'Заявления на расследование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Логи Email',
                'verbose_name_plural': 'Логи Email',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, verbose_name='Тип активности')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки за активность')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
            },
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='Лайк')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк/Дизлайк',
                'verbose_name_plural': 'Лайки/Дизлайки',
                'unique_together': {('user', 'profile')},
            },
        ),
    ]
