# Generated by Django 4.2.13 on 2024-08-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-priority'], 'verbose_name': 'Значок', 'verbose_name_plural': 'Значки'},
        ),
        migrations.AlterModelOptions(
            name='regrole',
            options={'verbose_name': 'Фракция', 'verbose_name_plural': 'Фракция'},
        ),
        migrations.AddField(
            model_name='badge',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.regrole', verbose_name='Фракция'),
        ),
    ]
