# Generated by Django 4.2.13 on 2024-08-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='passport_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на паспорт'),
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
