# Generated by Django 4.2.13 on 2024-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_investigationrequest_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationrequest',
            name='contact_details',
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тема заявления'),
        ),
    ]
