# Generated by Django 5.0.7 on 2024-07-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profileconfirmationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_viewed_changes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение истории изменений'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_viewed_news',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение новостей'),
        ),
    ]
