# Generated by Django 4.2.13 on 2024-08-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_badge_options_alter_regrole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, verbose_name='Тип активности')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки за активность')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
            },
        ),
    ]
