# Generated by Django 5.0.7 on 2024-08-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_regrole_options_alter_profile_reg_role'),
        ('profiles', '0003_profile_level_profile_rating_activitylog'),
    ]

    operations = [
    ]
