# Generated by Django 4.2.13 on 2024-07-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_remove_profile_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislike',
            options={'verbose_name': 'Лайки Дизлайки', 'verbose_name_plural': 'Лайки Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиля'},
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='change_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='new_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='old_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
