# Generated by Django 4.2.13 on 2024-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_department_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Игровой ник'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение профиля'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение должности'),
        ),
    ]
