# Generated by Django 4.2.13 on 2024-08-24 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_investigationrequest_contact_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationrequest',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя заявителя'),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия заявителя'),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='passport_link',
            field=models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на паспорт'),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$', 'Номер телефона должен быть в формате XXX-XXX-XXXX')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
