# Generated by Django 5.0.7 on 2024-08-23 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20240815_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_details', models.TextField(verbose_name='Контактные данные')),
                ('image', models.ImageField(blank=True, null=True, upload_to='investigation_requests/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('confirmed_by_admin', models.BooleanField(default=False, verbose_name='Подтверждено администратором')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='profiles.profile', verbose_name='Назначено профилю')),
            ],
            options={
                'verbose_name': 'Заявление на расследование',
                'verbose_name_plural': 'Заявления на расследование',
                'ordering': ['-created_at'],
            },
        ),
    ]
