# Generated by Django 4.2.13 on 2024-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ваше имя'),
        ),
    ]
