# Generated by Django 5.0.7 on 2024-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_investigationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя заявителя'),
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия заявителя'),
        ),
    ]
