# Generated by Django 4.2.13 on 2024-08-24 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_investigationrequest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationrequest',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{4,6}(-\\d{0,2})?$', 'Номер телефона должен содержать от 4 до 6 цифр, возможно с тире.')], verbose_name='Телефон'),
        ),
    ]
