# Generated by Django 4.2.13 on 2024-08-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_investigationrequest_response_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationrequest',
            name='confirmed_by_admin',
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_requests', to='profiles.profile', verbose_name='Закрыто профилем'),
        ),
    ]
