# Generated by Django 4.2.13 on 2024-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_investigationrequest_confirmed_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationrequest',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
    ]
