# Generated by Django 5.0.7 on 2024-07-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_likedislike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangelog',
            name='new_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='old_value',
            field=models.TextField(blank=True),
        ),
    ]
