# Generated by Django 5.0.7 on 2024-08-26 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_investigationrequest_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='profiles.profile', verbose_name='Выполняющий дело'),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_requests', to='profiles.profile', verbose_name='Закрыл дело'),
        ),
    ]
