# Generated by Django 5.0.7 on 2024-08-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_investigationrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_confirmation_requested',
            field=models.BooleanField(default=False, verbose_name='Запрос на подтверждение должности'),
        ),
    ]
