# Generated by Django 4.2.13 on 2024-07-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_alter_profilechangelog_new_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislike',
            options={'verbose_name': 'Лайк/Дизлайк', 'verbose_name_plural': 'Лайки/Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='../static/images/incognito.png', upload_to='users/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='change_type',
            field=models.CharField(max_length=255, verbose_name='Тип изменения'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together={('user', 'profile')},
        ),
    ]
