# Generated by Django 4.2.13 on 2024-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_updated_at_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
