# Generated by Django 5.0.7 on 2024-07-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='Контрактная служба открыта')),
            ],
            options={
                'verbose_name': 'Статус контрактной службы',
                'verbose_name_plural': 'Статус контрактной службы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Отдел')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('title', models.CharField(choices=[('sheriff', 'Шериф департамента'), ('colonel1', 'Полковник1'), ('colonel2', 'Полковник2'), ('colonel3', 'Полковник3'), ('lcolonel1', 'Подполковник1'), ('lcolonel2', 'Подполковник2'), ('lcolonel3', 'Подполковник3'), ('major1', 'Майор1'), ('major2', 'Майор2'), ('major3', 'Майор3'), ('major4', 'Майор4')], max_length=100, verbose_name='Звание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='department_staff', verbose_name='Фото')),
                ('job_title', models.TextField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('discord_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Discord')),
                ('vk_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на VK')),
            ],
            options={
                'verbose_name': 'Штаб',
                'verbose_name_plural': 'Штаб',
            },
        ),
        migrations.CreateModel(
            name='PoliceAcademyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('chief', 'Chief of PA'), ('dep_chief1', 'Dep.Chief of PA'), ('dep_chief2', 'Dep.Chief of PA')], max_length=10, verbose_name='Должность')),
                ('nickname', models.CharField(max_length=100, verbose_name='Ник')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='police_academy_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Должность ПА',
                'verbose_name_plural': 'Должности ПА',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Unsubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отписки')),
            ],
            options={
                'verbose_name': 'Отписка',
                'verbose_name_plural': 'Отписки',
            },
        ),
        migrations.CreateModel(
            name='ImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Важная информация',
                'verbose_name_plural': 'Важная информация',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_role_per_department'),
        ),
    ]
