# Generated by Django 4.2.13 on 2024-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['department', 'order'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role_per_department',
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('department', 'name')},
        ),
    ]
