# Generated by Django 5.0.7 on 2024-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractservicestatus',
            name='is_open',
        ),
        migrations.AddField(
            model_name='contractservicestatus',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('close', 'Закрыто')], default='close', max_length=5, verbose_name='Статус контрактной службы'),
        ),
    ]
