# Generated by Django 5.0.6 on 2024-07-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorsboard',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile'),
        ),
        migrations.AddField(
            model_name='importantinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='personalfile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile'),
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
