# Generated by Django 5.0.6 on 2024-07-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
    ]
