# Generated by Django 5.0.7 on 2024-08-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractservicestatus',
            options={'permissions': [('can_view_contract_service_status', 'Может просматривать статус контракта'), ('can_edit_contract_service_status', 'Может редактировать статус контракта')], 'verbose_name': 'Статус контракта', 'verbose_name_plural': 'Статус контракта'},
        ),
        migrations.AlterModelOptions(
            name='cpdposition',
            options={'permissions': [('can_view_cpd_positions', 'Может просматривать должности CPD'), ('can_edit_cpd_positions', 'Может редактировать должности CPD')], 'verbose_name': 'Должность CPD', 'verbose_name_plural': 'Должности CPD'},
        ),
        migrations.AlterModelOptions(
            name='dbposition',
            options={'permissions': [('can_view_db_positions', 'Может просматривать должности DB'), ('can_edit_db_positions', 'Может редактировать должности DB')], 'verbose_name': 'Должность DB', 'verbose_name_plural': 'Должности DB'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_view_departments', 'Может просматривать отделы'), ('can_edit_departments', 'Может редактировать отделы')], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'permissions': [('can_view_department_staff', 'Может просматривать штаб'), ('can_edit_department_staff', 'Может редактировать штаб')], 'verbose_name': 'Штаб', 'verbose_name_plural': 'Штаб'},
        ),
        migrations.AlterModelOptions(
            name='importantnotification',
            options={'permissions': [('can_view_important_notifications', 'Может просматривать важную информацию'), ('can_edit_important_notifications', 'Может редактировать важную информацию')], 'verbose_name': 'Важная информация', 'verbose_name_plural': 'Важная информация'},
        ),
        migrations.AlterModelOptions(
            name='policeacademyposition',
            options={'permissions': [('can_view_pa_positions', 'Может просматривать должности ПА'), ('can_edit_pa_positions', 'Может редактировать должности ПА')], 'verbose_name': 'Должность ПА', 'verbose_name_plural': 'Должности ПА'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['department', 'order'], 'permissions': [('can_view_roles', 'Может просматривать должности'), ('can_edit_roles', 'Может редактировать должности')], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='swatposition',
            options={'permissions': [('can_view_swat_positions', 'Может просматривать должности SWAT'), ('can_edit_swat_positions', 'Может редактировать должности SWAT')], 'verbose_name': 'Должность SWAT', 'verbose_name_plural': 'Должности SWAT'},
        ),
    ]
