# Generated by Django 4.2.13 on 2024-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
