# Generated by Django 4.2.13 on 2024-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_contractservicestatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEBPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('commander', 'Commander of SEB'), ('dep_commander1', 'Dep.Com. of SEB'), ('dep_commander2', 'Dep.Com. of SEB')], max_length=20, verbose_name='Должность')),
                ('nickname', models.CharField(max_length=100, verbose_name='Ник')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seb_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Должность SEB',
                'verbose_name_plural': 'Должности SEB',
                'permissions': [('can_view_swat_positions', 'Может просматривать должности SEB'), ('can_edit_swat_positions', 'Может редактировать должности SEB')],
            },
        ),
    ]
