# Generated by Django 5.0.6 on 2024-07-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_employeeprofile_department_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorsboard',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile'),
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
