# Generated by Django 4.2.13 on 2024-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblevents',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
