# Generated by Django 4.2.13 on 2024-07-24 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_remove_contractservicestatus_is_open_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Unsubscription',
        ),
        migrations.AlterModelOptions(
            name='contractservicestatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='contractservicestatus',
            name='status',
        ),
        migrations.AddField(
            model_name='contractservicestatus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractservicestatus',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
