# Generated by Django 4.2.13 on 2024-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_role_options_alter_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceAcademyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('chief', 'Chief of PA'), ('dep_chief1', 'Dep.Chief of PA'), ('dep_chief2', 'Dep.Chief of PA')], max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='police_academy_photos/')),
            ],
        ),
    ]
