# Generated by Django 4.2.13 on 2024-07-24 14:17

from django.db import migrations, models
import django.utils.crypto
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_subscriber_remove_contractservicestatus_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(default=django.utils.crypto.get_random_string, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
