# Generated by Django 4.2.13 on 2024-08-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_event_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
