# Generated by Django 4.2.13 on 2024-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_policeacademyposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSFPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('chiefpa', 'Chief of PA'), ('dep_chiefpa1', 'Dep.Chief of PA'), ('dep_chiefpa2', 'Dep.Chief of PA'), ('chiefcpd', 'Chief of CPD'), ('dep_chiefcpd1', 'Dep.Chief of CPD'), ('dep_chiefcpd2', 'Dep.Chief of CPD'), ('head', 'HEAD of DB'), ('dep_head1', 'Dep.HEAD of DB'), ('dep_head2', 'Dep.HEAD of DB'), ('commander', 'Chief of PA'), ('dep_commander1', 'Dep. Commander of SWAT'), ('dep_commander2', 'Dep. Commander of SWAT')], max_length=20)),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='management/')),
            ],
        ),
        migrations.DeleteModel(
            name='PoliceAcademyPosition',
        ),
    ]
