# Generated by Django 4.2.13 on 2024-07-24 14:19

import departments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_unsubscribetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='token',
            field=models.CharField(default=departments.models.generate_token, max_length=64, unique=True),
        ),
    ]
