# Generated by Django 5.0.7 on 2024-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_policeacademyposition_delete_managementsfpd'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('sheriff', 'Шериф департамента'), ('colonel1', 'Полковник1'), ('colonel2', 'Полковник2'), ('colonel3', 'Полковник3'), ('lcolonel1', 'Подполковник1'), ('lcolonel2', 'Подполковник2'), ('lcolonel3', 'Подполковник3'), ('major1', 'Майор1'), ('major2', 'Майор2'), ('major3', 'Майор3'), ('major4', 'Майор4')], max_length=100)),
                ('photo', models.ImageField(upload_to='department_staff')),
                ('discord_url', models.URLField(blank=True, null=True)),
                ('vk_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
