# Generated by Django 4.2.13 on 2024-07-24 14:26

import departments.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_unsubscribetoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractservicestatus',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус контракта'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='token',
            field=models.CharField(default=departments.models.generate_token, max_length=64, unique=True, verbose_name='Токен'),
        ),
    ]
