# Generated by Django 4.2.13 on 2024-07-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_alter_contractservicestatus_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractservicestatus',
            options={'verbose_name': 'Статус контракта', 'verbose_name_plural': 'Статус контракта'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписки на рассылку', 'verbose_name_plural': 'Подписки на рассылку'},
        ),
        migrations.AlterModelOptions(
            name='unsubscribetoken',
            options={'verbose_name': 'Токен отписки', 'verbose_name_plural': 'Токен отписки'},
        ),
    ]
