# Generated by Django 5.0.7 on 2024-07-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_departmentstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='department_staff'),
        ),
    ]
