# Generated by Django 4.2.13 on 2024-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_alter_departmentstaff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='job_title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
