# Generated by Django 5.0.7 on 2024-07-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_departmentstaff_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'verbose_name': 'Штаб', 'verbose_name_plural': 'Штаб'},
        ),
        migrations.AlterModelOptions(
            name='policeacademyposition',
            options={'verbose_name': 'Должность ПА', 'verbose_name_plural': 'Должности ПА'},
        ),
    ]
