# Generated by Django 4.2.13 on 2024-07-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_alter_department_name_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantinfo',
            options={'verbose_name': 'Важная информация', 'verbose_name_plural': 'Важная информация'},
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='discord_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Discord'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='job_title',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='department_staff', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='title',
            field=models.CharField(choices=[('sheriff', 'Шериф департамента'), ('colonel1', 'Полковник1'), ('colonel2', 'Полковник2'), ('colonel3', 'Полковник3'), ('lcolonel1', 'Подполковник1'), ('lcolonel2', 'Подполковник2'), ('lcolonel3', 'Подполковник3'), ('major1', 'Майор1'), ('major2', 'Майор2'), ('major3', 'Майор3'), ('major4', 'Майор4')], max_length=100, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='vk_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на VK'),
        ),
        migrations.AlterField(
            model_name='importantinfo',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='importantinfo',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='importantinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='importantinfo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='policeacademyposition',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='policeacademyposition',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='policeacademyposition',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='police_academy_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='policeacademyposition',
            name='position',
            field=models.CharField(choices=[('chief', 'Chief of PA'), ('dep_chief1', 'Dep.Chief of PA'), ('dep_chief2', 'Dep.Chief of PA')], max_length=10, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел'),
        ),
    ]
